Split up remaining pieces in public/index.php
doctrine/automatic-releases pull request #15
Opened 2019-04-13 15:53 UTC by jwage

Fixes #4

TODO:

- [ ] get feedback from Marco on direction
- [ ] Add tests

2019-04-13 21:53 UTC, Ocramius requested changes

2019-04-13 21:53 UTC, Ocramius commented on src/Git/CleanBuildDir.php
> +        (new Process(['rm', '-rf', $buildDir]))
At this point, we need to assert that `$buildDir` is a directory, before performing something this scary :)

2019-04-13 21:53 UTC, Ocramius commented on src/Git/CloneRepository.php
> +        string $gitAuthorName,
These values should be asserted upon, or we should have value types introduced

2019-04-13 21:53 UTC, Ocramius commented on src/Git/CreateTag.php
> +        string $tagName,
We need to assert on the tag being a non-empty string

2019-04-13 21:55 UTC, Ocramius commented
> get feedback from Marco on direction

As you can see from the structure of the code that was ported, it is extremely hard to test in isolation. That will be a pain, but we'll need to go through it. Also, I think that the various `string` parameters, especially when representing a `Directory` or a `GitRepositoryRootPath`, we should have value types representing them, reducing the risk of incorrect strings being passed around.

2019-04-13 22:05 UTC, jwage commented
Cool. That is aligned with what I was thinking needs to happen next. I will keep working on it.

2020-08-02 00:20 UTC, Ocramius commented
Closing here: this has been implemented in https://github.com/laminas/automatic-releases/pull/1, which splits the application into multiple independent CLI commands.

2020-08-02 00:20 UTC, closed without merging